# ASP.NET Core (.NET Framework)
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)
- task: Docker@2
  inputs:
    containerRegistry: 'srcmyapp'
    repository: 'WithDatabaseDemo-master'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'